### PR TITLE
implemented logic circuit and parsing of SDD

### PR DESCRIPTION
**Pull request by n28div**
Parsing of SDD is directly performed from the standard SDD file instead of using pySDD and additional dependencies. 
Due to issue #311 the circuit will not work as expected. A quick and dirty patch is to update `cirkit/backend/torch/layers/input.py` 

line 228:
```
- return self.semiring.map_from(x, LSESumSemiring)
+ return self.semiring.map_from(x, SumProductSemiring)
```

and line 328:
```
- logits = torch.log(self.probs()) if self.logits is None else self.logits()
+ logits = self.probs() if self.logits is None else self.logits()
```

side-effects have not been considered though.

### CODE REVIEW

**Comment by loreloc** [comment]
Hi Nicolas,
I have just merged a PR that unifies MixingLayer and DenseLayer in a single class SumLayer. Therefore, could you please try replacing the mixing layers with sum layers in your implementation for this?
Thank you!

**Comment by loreloc** [comment]
Hi Nicolas,
did you try the code?
This line does not seem correct
https://github.com/april-tools/cirkit/blob/fe5358ca904f42ec128e11cb041170be6c99433f/cirkit/symbolic/circuit.py#L960
The number of input and output units should always be 1 in your case, but arity > 1.

**Comment by n28div** [comment]
Yep, on my tests it did work just the same as before. You are right though, I misinterpreted the parameter. The new commit should be ok.

**Comment by loreloc** [comment]
Hi Nicolas,
is there something else that needs to be done for this PR?
Otherwise, I can have a look more in detail and merge it by the end of this week.

**Comment by n28div** [comment]
Hi Lorenzo, yes you are right. The notebook I added uses the plotting function of #322. I added the dependency there and merged it into this PR

**Comment by n28div** [comment]
Sure! Go ahead and let me know if there's anything that I can help with

**Pull request merged**
